paginate_per_page: 18
default_per_page: 10
window: 2
param_name: "q[page]"
book:
  num_page_min: 1
  num_page_max: 10000
  cover_default: "book.jpg"
  size: "330x250"
activities:
  followed: followed
  unfollowed: unfollowed
  reviewed: reviewed
  commented: commented
  read: read
  favorited: favorited
  per_page: 10
  book: book
  review: review
  user: user
validates:
  comment:
    minlength: 10
  review:
    minlength: 10
category:
  per_page: 10
relationships: ["following", "followers"]
user:
  avatar_default: "user.png"
  size: "50x50"
book_users:
  unread: unread
  readed: mark_as_readed
  reading: mark_as_reading
  favorited: add_to_favorites
  unfavorited: remove_from_favorites
